apiVersion: v1
kind: Service
metadata:
  name: vproapp
  labels:
    app: app
    {{- include "app-chart.labels" . | nindent 4 }}
spec:
  selector:
    app: app
  ports:
    - port: {{ .Values.app.port }}
      targetPort: app-port
      protocol: TCP
  type: ClusterIP
