apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  labels:
    {{- include "vprofile.labels" . | nindent 4 }}
type: Opaque
data:
  mysql-root-password: {{ .Values.secrets.mysqlRootPassword | b64enc | quote }}
  rabbitmq-default-pass: {{ .Values.secrets.rabbitmqDefaultPass | b64enc | quote }}
