name: "Deploy to AWS"
on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AWS_IAM_ROLE: ${{ secrets.AWS_IAM_ROLE }}
  AWS_REGISTRY: ${{ secrets.REGISTRY }}
  AWS_REGION: us-east-1
  ECR_REPOSITORY: gitops-project
  EKS_CLUSTER: gitops-eks-cluster

permissions:
  id-token: write
  contents: read

jobs:
  Testing:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Maven Testing
        run: mvn test

      - name: Checkstyle
        run: mvn checkstyle:checkstyle

      - name: Setup JAVA 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Setup SonarQube
        uses: sonarsource/sonarqube-scan-action@v4
        with:
          projectBaseDir: .
          args: >
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
            -Dsonar.java.binaries=target/classes/
            -Dsonar.junit.reportsPath=target/surefire-reports/ 
            -Dsonar.jacoco.reportsPath=target/jacoco.exec
            -Dsonar.java.checkstyle.reportPaths=target/checkstyle-result.xml
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      # COMMENT FOR PRACTICE PURPOSES
      # - name: SonarQube Quality Gate check
      #   id: sonarqube-quality-gate-check
      #   uses: sonarsource/sonarqube-quality-gate-action@master
      #   with:
      #     pollingTimeoutSec: 600
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  Build_and_Publish:
    needs: Testing
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@ec61189d14ec14c8efccab744f656cffd0e33f37
        with:
          role-to-assume: ${{ env.AWS_IAM_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@19d944daaa35f0fa1d3f7f8af1d3f2e5de25c5b7

      - name: Build and Push Docker Image to ECR
        env:
          REGISTRY: ${{ env.AWS_REGISTRY }}
          REPOSITORY: ${{ env.ECR_REPOSITORY }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

  Deploy_to_EKS:
    needs: Build_and_Publish
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@ec61189d14ec14c8efccab744f656cffd0e33f37
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Get Kubeconfig
        run: aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name ${{ env.EKS_CLUSTER }}

      - name: Login to Amazon ECR
        id: login-ecr
        run: | 
          kubectl create secret docker-registry regcred \
            --docker-server=${{ env.AWS_REGISTRY }} \
            --docker-username=AWS \
            --docker-password=$(aws ecr get-login-password) \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Install Helm Chart
        uses: bitovi/github-actions-deploy-eks-helm@29f556cf128eb1b42f834caf13b60a630ee2a20b
        with:
          aws-region: ${{ env.AWS_REGION }}
          cluster-name: ${{ env.EKS_CLUSTER }}
          chart-path: ./helm/app-chart/
          namespace: default
          values: app.image=${{ env.AWS_REGISTRY }}/${{ env.ECR_REPOSITORY }},app.tag=${{ github.sha }},secrets.mysqlRootPassword=${{ secrets.MYSQL_ROOT_PASSWORD }},secrets.rabbitmqDefaultPass=${{ secrets.RABBITMQ_PASS }}
          name: app-release